GET http://localhost:3003/api/blogs
Content-Type: application/json

###

POST http://localhost:3003/api/blogs
Content-Type: application/json


  {
    "title": "example blog2",
    "author": "john doe2",
    "url": "gogol.co2"
  }

###
GET http://localhost:3003/api/users
Content-Type: application/json

###
POST http://localhost:3003/api/users
Content-Type: application/json

  {
    "username": "personone",
    "name": "Person One",
    "password": "password123"
  }
